### ISSUE TITLE
Serve plotly graphs for downloads

### ISSUE THREAD

**Issue by venomslasher** [Bluejee/LIBS_Analysis_Website#4]
Please view the [Contributing Guidelines](https://github.com/Bluejee/LIBS_Analysis_Website/blob/main/CONTRIBUTING.md) for information on Contributing.

**Is your feature request related to a problem? Please describe.**
The download section needs to have a graph which can be downloaded for reference.
Providing only data is not always easy to handle.

**Describe the solution you'd like**
Use plotly to plot and export the graph as an html file which is zipped along with the other downloadable files.

**Describe alternatives you've considered**
nil

**Additional context**

**Comment by Bluejee** [comment]
> I think I can create a function for this.

Okay. Ill Assign you to this issue.
